# The Basics

In [ ]:
import numpy as np

a = np.array([1, 2, 3], dtype='int16')
print(a, end='\n')
b = np.array([[9.0, 8, 7.0], [6.0, 5.0, 4.0]])
print(b)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
# Get shape
print(b.shape)

(2, 3)


In [ ]:
# Get type
print(b.dtype)

float64


In [ ]:
# Get size
print(a.itemsize)

2


In [ ]:
# Get number of elements
print(a.size)

3


In [ ]:
# Get total size
print(a.size * a.itemsize)
print(a.nbytes)

6
6


# Accessing/Changing specific elements, rows, columns

In [ ]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
# Get a specific element [r, c]
print(a[1, 5])
print(a[1, -2])

20
20


In [ ]:
# 3-d example
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

In [ ]:
# Get specific element (work outside in)
print(b[1, 0, 1])

In [ ]:
# Get a specific row
print(a[0, :])

[1 2 1 4 5 6 7]


In [ ]:
# Get a specific column
print(a[:, 2])

[1 2]


In [ ]:
# Gettting a little more fancy [startindex:endindex:stepsize]
print(a[0, 1:6:2])

a[1, 5] = 20
print(a)

a[:, 2] = 5
print(a)

a[:, 2] = [1, 2]
print(a)

[2 4 6]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
# replace
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different Types of Arrays

In [ ]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any other number
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
# Any other numer (full_like)
print(a)
np.full_like(a, 4)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Radom decimal numbers
np.random.rand(4,2)

array([[0.94036717, 0.7295753 ],
       [0.27523076, 0.98130277],
       [0.40341144, 0.39366643],
       [0.13168404, 0.92509375]])

In [ ]:
# Random Integer values
np.random.randint(-2,7, size=(3,3))

array([[ 0,  3,  4],
       [ 1, -2,  4],
       [ 4,  6,  5]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
r1
r2 = np.repeat([1, 2, 3], 3, axis=0)
r2

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [ ]:
output = np.ones((5, 5))

z = np.zeros((3, 3))
z[1, 1] = 9

output[1:4,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays

In [ ]:
a = np.array([1, 2, 3])
b = a.copy()
b[0]


# Mathematics

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a += 2
a

array([5, 6, 7, 8])

In [ ]:
a - 2

array([3, 4, 5, 6])

In [ ]:
a * 2

array([10, 12, 14, 16])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

array([-0.99999992])

##### Linear Algebra

In [ ]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

## Statistics

In [ ]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.min(stats, axis=1)

array([1, 4])

In [ ]:
np.max(stats)

6

In [ ]:
np.max(stats,axis=0)

array([4, 5, 6])

In [ ]:
np.sum(stats)

21

In [ ]:
np.sum(stats,axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal stack
v1 = np.ones((2,4))
v2 = np.zeros((2,2))

np.hstack((v1,v2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

##### Load Data from File

In [ ]:
filedata = np.genfromtxt('TestGraph.txt', delimiter=' ')
filedata = filedata.astype('int8')
filedata

array([[0, 1, 1, 1, 0],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [0, 1, 1, 1, 0]], dtype=int8)

##### Boolean Masking and Advanced Index

In [ ]:
filedata > 0

array([[False,  True,  True,  True, False],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [False,  True,  True,  True, False]])

In [ ]:
filedata[filedata > 0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [ ]:
## You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1, 2, 8]]

array([2, 3, 9])

In [ ]:
np.any(filedata > 0, axis=0)

array([ True,  True,  True,  True,  True])

In [ ]:
np.all(filedata>0,axis=0)

array([False, False, False, False, False])

In [ ]:
((filedata > 0) & (filedata < 2))

array([[False,  True,  True,  True, False],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [False,  True,  True,  True, False]])